// Shared tag list used across the app.
// Import from here in TagSelectionScreen, ProfileScreen, and any other screen
// that needs to display or select tags. Never duplicate this list elsewhere.

export const AVAILABLE_TAGS = [
  "🎨 Art",
  "🔭 Astronomy",
  "🏖️ Beach",
  "🍹 Beach Bars",
  "🍺 Beer",
  "🎲 Board Games",
  "🎳 Bowling",
  "🍔 Burgers",
  "🏕️ Camping",
  "💼 Career Focused",
  "🎠 Carnivals",
  "🐱 Cat Lover",
  "😌 Chill Vibes",
  "🌆 City Life",
  "☕ Coffee",
  "🍹 Cocktails",
  "🍳 Cooking",
  "🏞️ Country Life",
  "🚴 Cycling",
  "🎯 Darts",
  "🍰 Desserts",
  "🐶 Dog Lover",
  "🌅 Early Bird",
  "👨‍👩‍👧‍👦 Family Oriented",
  "🎪 Festivals",
  "🎣 Fishing",
  "🏋️ Fitness",
  "🎮 Gaming",
  "🏌️ Golf",
  "🥗 Healthy Eating",
  "🌋 Hiking",
  "🏡 Homebody",
  "🏠 Homeowner",
  "🎤 Karaoke",
  "🚣 Kayaking",
  "🪁 Kite Flying",
  "🎸 Live Music",
  "🗻 Mountain Climbing",
  "🎬 Movies",
  "🎵 Music",
  "🌿 Nature",
  "🌙 Night Owl",
  "🌃 Nightlife",
  "🌊 Ocean Views",
  "🎉 Party",
  "🐾 Pet Lover",
  "📸 Photography",
  "🍕 Pizza",
  "🎱 Pool/Billiards",
  "🧩 Puzzles",
  "📚 Reading",
  "🚗 Road Trips",
  "🧗 Rock Climbing",
  "🏃 Running",
  "⛵ Sailing",
  "🤿 Scuba Diving",
  "⛷️ Skiing",
  "🛹 Skateboarding",
  "🏂 Snowboarding",
  "🎿 Snowshoeing",
  "⚽ Sports",
  "🌌 Stargazing",
  "🎓 Student Life",
  "🏖️ Sunbathing",
  "🏄 Surfing",
  "🍣 Sushi",
  "🏊 Swimming",
  "🌮 Tacos",
  "🎭 Theater",
  "🎢 Theme Parks",
  "✈️ Travel",
  "🥑 Vegan",
  "🌱 Vegetarian",
  "🍷 Wine",
  "🧘 Yoga",
];
